<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>002</title>
</head>
<style>
    @page {
        margin: -20px;
        /* margin-left: -12px; */
        /* margin-top: -60px;
        margin-left: -12px; */
    }
    /* body { margin: -10px; } */
    body { margin: -10px; padding: 10px; }
</style>
<body>
<img style="position:absolute;top:0.00in;left:0.00in;width:4.93in;height:3.52in" src="http://darwin.test/garrido-transportes/public/img/002/vi_1.png" />
<img style="position:absolute;top:3.68in;left:0.45in;width:1.52in;height:0.34in" src="http://darwin.test/garrido-transportes/public/img/002/vi_2.png" />
<img style="position:absolute;top:3.78in;left:0.53in;width:1.36in;height:0.16in" src="http://darwin.test/garrido-transportes/public/img/002/vi_3.png" />
<div style="position:absolute;top:3.78in;left:0.88in;width:0.74in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial-BoldMT;color:#000000">EMPRESA </span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.68in;left:3.89in;width:0.96in;height:0.34in" src="http://darwin.test/garrido-transportes/public/img/002/vi_4.png" />
<img style="position:absolute;top:3.78in;left:3.97in;width:0.80in;height:0.16in" src="http://darwin.test/garrido-transportes/public/img/002/vi_5.png" />
<div style="position:absolute;top:3.78in;left:4.12in;width:0.54in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial-BoldMT;color:#000000">CARGO</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.68in;left:6.23in;width:0.70in;height:0.34in" src="http://darwin.test/garrido-transportes/public/img/002/vi_6.png" />
<img style="position:absolute;top:3.78in;left:6.31in;width:0.54in;height:0.16in" src="http://darwin.test/garrido-transportes/public/img/002/vi_7.png" />
<div style="position:absolute;top:3.78in;left:6.35in;width:0.50in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial-BoldMT;color:#000000">FECHA</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.67in;left:0.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_8.png" />
<img style="position:absolute;top:3.67in;left:0.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_9.png" />
<img style="position:absolute;top:3.67in;left:0.45in;width:1.52in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_10.png" />
<img style="position:absolute;top:3.67in;left:1.97in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_11.png" />
<img style="position:absolute;top:3.67in;left:1.98in;width:1.90in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_12.png" />
<img style="position:absolute;top:3.67in;left:3.88in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_13.png" />
<img style="position:absolute;top:3.67in;left:3.89in;width:0.96in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_14.png" />
<img style="position:absolute;top:3.67in;left:4.85in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_15.png" />
<img style="position:absolute;top:3.67in;left:4.85in;width:1.37in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_16.png" />
<img style="position:absolute;top:3.67in;left:6.22in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_17.png" />
<img style="position:absolute;top:3.67in;left:6.23in;width:0.70in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_18.png" />
<img style="position:absolute;top:3.67in;left:6.93in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_19.png" />
<img style="position:absolute;top:3.67in;left:6.94in;width:1.78in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_20.png" />
<img style="position:absolute;top:3.67in;left:8.71in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_21.png" />
<img style="position:absolute;top:3.67in;left:8.71in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_22.png" />
<img style="position:absolute;top:3.68in;left:0.44in;width:0.01in;height:0.34in" src="http://darwin.test/garrido-transportes/public/img/002/vi_23.png" />
<img style="position:absolute;top:3.68in;left:1.97in;width:0.01in;height:0.34in" src="http://darwin.test/garrido-transportes/public/img/002/vi_24.png" />
<img style="position:absolute;top:3.68in;left:3.88in;width:0.01in;height:0.34in" src="http://darwin.test/garrido-transportes/public/img/002/vi_25.png" />
<img style="position:absolute;top:3.68in;left:4.85in;width:0.01in;height:0.34in" src="http://darwin.test/garrido-transportes/public/img/002/vi_26.png" />
<img style="position:absolute;top:3.68in;left:6.22in;width:0.01in;height:0.34in" src="http://darwin.test/garrido-transportes/public/img/002/vi_27.png" />
<img style="position:absolute;top:3.68in;left:6.93in;width:0.01in;height:0.34in" src="http://darwin.test/garrido-transportes/public/img/002/vi_28.png" />
<img style="position:absolute;top:3.68in;left:8.71in;width:0.01in;height:0.34in" src="http://darwin.test/garrido-transportes/public/img/002/vi_29.png" />
<img style="position:absolute;top:4.03in;left:0.45in;width:1.52in;height:0.34in" src="http://darwin.test/garrido-transportes/public/img/002/vi_30.png" />
<img style="position:absolute;top:4.05in;left:0.53in;width:1.36in;height:0.16in" src="http://darwin.test/garrido-transportes/public/img/002/vi_31.png" />
<div style="position:absolute;top:4.05in;left:0.91in;width:0.63in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial-BoldMT;color:#000000">NOMBRE</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:4.21in;left:0.53in;width:1.36in;height:0.16in" src="http://darwin.test/garrido-transportes/public/img/002/vi_32.png" />
<div style="position:absolute;top:4.21in;left:0.74in;width:0.98in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial-BoldMT;color:#000000">TRABAJADOR</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:4.03in;left:6.23in;width:0.70in;height:0.34in" src="http://darwin.test/garrido-transportes/public/img/002/vi_33.png" />
<img style="position:absolute;top:4.13in;left:6.31in;width:0.54in;height:0.16in" src="http://darwin.test/garrido-transportes/public/img/002/vi_34.png" />
<div style="position:absolute;top:4.13in;left:6.44in;width:0.31in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial-BoldMT;color:#000000">RUT</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:4.03in;left:0.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_35.png" />
<img style="position:absolute;top:4.03in;left:0.45in;width:1.52in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_36.png" />
<img style="position:absolute;top:4.03in;left:1.97in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_37.png" />
<img style="position:absolute;top:4.03in;left:1.98in;width:1.90in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_38.png" />
<img style="position:absolute;top:4.03in;left:3.88in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_39.png" />
<img style="position:absolute;top:4.03in;left:3.89in;width:0.96in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_40.png" />
<img style="position:absolute;top:4.03in;left:4.85in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_41.png" />
<img style="position:absolute;top:4.03in;left:4.85in;width:1.37in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_42.png" />
<img style="position:absolute;top:4.03in;left:6.22in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_43.png" />
<img style="position:absolute;top:4.03in;left:6.23in;width:0.70in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_44.png" />
<img style="position:absolute;top:4.03in;left:6.93in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_45.png" />
<img style="position:absolute;top:4.03in;left:6.94in;width:1.78in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_46.png" />
<img style="position:absolute;top:4.03in;left:8.71in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_47.png" />
<img style="position:absolute;top:4.03in;left:0.44in;width:0.01in;height:0.35in" src="http://darwin.test/garrido-transportes/public/img/002/vi_48.png" />
<img style="position:absolute;top:4.38in;left:0.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_49.png" />
<img style="position:absolute;top:4.38in;left:0.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_50.png" />
<img style="position:absolute;top:4.38in;left:0.45in;width:1.52in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_51.png" />
<img style="position:absolute;top:4.03in;left:1.97in;width:0.01in;height:0.35in" src="http://darwin.test/garrido-transportes/public/img/002/vi_52.png" />
<img style="position:absolute;top:4.38in;left:1.97in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_53.png" />
<img style="position:absolute;top:4.38in;left:1.98in;width:4.25in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_54.png" />
<img style="position:absolute;top:4.03in;left:6.22in;width:0.01in;height:0.35in" src="http://darwin.test/garrido-transportes/public/img/002/vi_55.png" />
<img style="position:absolute;top:4.38in;left:6.22in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_56.png" />
<img style="position:absolute;top:4.38in;left:6.23in;width:0.70in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_57.png" />
<img style="position:absolute;top:4.03in;left:6.93in;width:0.01in;height:0.35in" src="http://darwin.test/garrido-transportes/public/img/002/vi_58.png" />
<img style="position:absolute;top:4.38in;left:6.93in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_59.png" />
<img style="position:absolute;top:4.38in;left:6.94in;width:1.78in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_60.png" />
<img style="position:absolute;top:4.03in;left:8.71in;width:0.01in;height:0.35in" src="http://darwin.test/garrido-transportes/public/img/002/vi_61.png" />
<img style="position:absolute;top:4.38in;left:8.71in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_62.png" />
<img style="position:absolute;top:4.38in;left:8.71in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_63.png" />
<div style="position:absolute;top:4.47in;left:0.45in;width:4.37in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000">1. Evalúa tu posible exposición antes de venir a trabajar </span></SPAN><br/></div>
<div style="position:absolute;top:4.81in;left:0.72in;width:0.12in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.82in;left:0.99in;width:3.36in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">¿Ha </span></SPAN><br/></div>
<div style="position:absolute;top:4.82in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:0.38in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">tenido </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.82in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:0.89in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">contacto </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.82in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:1.56in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">cercano </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.82in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:2.19in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">(a </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.82in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:2.42in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">menos </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.82in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:2.97in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">de </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.82in;left:0.99in;width:3.36in;line-height:0.19in;"><DIV style="position:relative; left:3.23in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">2</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></DIV><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">metros) </span></SPAN><br/></div>
<div style="position:absolute;top:5.00in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:0.59in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">con </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.00in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:0.90in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">personas </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.00in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:1.60in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">que </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.00in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:1.93in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">estén </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.00in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:2.37in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">enfermas </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.00in;left:0.99in;width:3.36in;line-height:0.19in;"><DIV style="position:relative; left:3.07in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">con</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></DIV><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">síntomas </span></SPAN><br/></div>
<div style="position:absolute;top:5.17in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:0.69in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">similares </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.17in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:1.37in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">a </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.17in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:1.54in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">la </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.17in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:1.73in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">gripe </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.17in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:2.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">en </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.17in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:2.40in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">las </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.17in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:2.67in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">últimas </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.17in;left:0.99in;width:3.36in;line-height:0.19in;"><DIV style="position:relative; left:3.23in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">2</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></DIV><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">semanas?</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.51in;left:0.72in;width:0.12in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.52in;left:0.99in;width:3.36in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">En </span></SPAN><br/></div>
<div style="position:absolute;top:5.52in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:0.26in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">caso </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.52in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:0.67in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">afirmativo, </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.52in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:1.44in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">¿sabe </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.52in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:1.95in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">si </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.52in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:2.13in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">se </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.52in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:2.37in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">han </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.52in;left:0.99in;width:3.36in;line-height:0.21in;"><DIV style="position:relative; left:2.71in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">hecho </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:5.52in;left:0.99in;width:3.36in;line-height:0.19in;"><DIV style="position:relative; left:3.20in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">la</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></DIV><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">prueba COVID-19?</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">Ha viajado fuera de Chile las últimas 2 semanas?</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.87in;left:0.72in;width:0.12in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.51in;left:0.45in;width:4.37in;line-height:0.22in;"><DIV style="position:relative; left:4.10in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#20201e">NO</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#20201e"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:4.86in;left:4.60in;width:0.28in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Segoe UI Symbol;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Segoe UI Symbol;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:5.49in;left:4.59in;width:0.28in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Segoe UI Symbol;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Segoe UI Symbol;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:5.73in;left:4.59in;width:0.28in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Segoe UI Symbol;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Segoe UI Symbol;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:4.47in;left:4.88in;width:0.39in;height:1.87in" src="http://darwin.test/garrido-transportes/public/img/002/vi_64.png" />
<img style="position:absolute;top:4.47in;left:4.88in;width:0.39in;height:0.21in" src="http://darwin.test/garrido-transportes/public/img/002/vi_65.png" />
<div style="position:absolute;top:4.51in;left:5.05in;width:0.18in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#c61d2c">SI</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#c61d2c"> </span><br/></SPAN></div>
<img style="position:absolute;top:4.68in;left:4.88in;width:0.39in;height:0.18in" src="http://darwin.test/garrido-transportes/public/img/002/vi_66.png" />
<img style="position:absolute;top:4.86in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_67.png" />
<div style="position:absolute;top:4.86in;left:5.01in;width:0.28in;line-height:0.20in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Segoe UI Symbol;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Segoe UI Symbol;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:5.06in;left:4.88in;width:0.39in;height:0.17in" src="http://darwin.test/garrido-transportes/public/img/002/vi_68.png" />
<img style="position:absolute;top:5.24in;left:4.88in;width:0.39in;height:0.28in" src="http://darwin.test/garrido-transportes/public/img/002/vi_69.png" />
<img style="position:absolute;top:5.52in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_70.png" />
<div style="position:absolute;top:5.54in;left:5.01in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:5.71in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_71.png" />
<div style="position:absolute;top:5.74in;left:5.01in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:4.47in;left:5.37in;width:0.25in;line-height:0.27in;"><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:Arial;color:#ff0000">→</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.53in;left:5.73in;width:0.18in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">Si</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.53in;left:6.01in;width:0.77in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">respondió</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.53in;left:6.88in;width:0.18in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">SI</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.53in;left:7.16in;width:0.13in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">a</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.53in;left:7.38in;width:0.53in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">alguna</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.53in;left:5.37in;width:3.38in;line-height:0.22in;"><DIV style="position:relative; left:2.63in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">de </span></SPAN></DIV><br/></div>
<div style="position:absolute;top:4.53in;left:5.37in;width:3.38in;line-height:0.20in;"><DIV style="position:relative; left:2.95in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">estas</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></DIV><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">preguntas, por favor hable con su supervisor.</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<img style="position:absolute;top:4.46in;left:0.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_72.png" />
<img style="position:absolute;top:4.46in;left:0.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_73.png" />
<img style="position:absolute;top:4.46in;left:0.45in;width:3.99in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_74.png" />
<img style="position:absolute;top:4.46in;left:4.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_75.png" />
<img style="position:absolute;top:4.46in;left:4.45in;width:0.43in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_76.png" />
<img style="position:absolute;top:4.46in;left:4.88in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_77.png" />
<img style="position:absolute;top:4.46in;left:4.88in;width:0.39in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_78.png" />
<img style="position:absolute;top:4.46in;left:5.28in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_79.png" />
<img style="position:absolute;top:4.46in;left:5.28in;width:3.43in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_80.png" />
<img style="position:absolute;top:4.46in;left:8.71in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_81.png" />
<img style="position:absolute;top:4.46in;left:8.71in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_82.png" />
<img style="position:absolute;top:4.47in;left:0.44in;width:0.01in;height:0.16in" src="http://darwin.test/garrido-transportes/public/img/002/vi_83.png" />
<img style="position:absolute;top:4.47in;left:4.44in;width:0.01in;height:0.16in" src="http://darwin.test/garrido-transportes/public/img/002/vi_84.png" />
<img style="position:absolute;top:4.47in;left:4.88in;width:0.01in;height:0.16in" src="http://darwin.test/garrido-transportes/public/img/002/vi_85.png" />
<img style="position:absolute;top:4.47in;left:5.28in;width:0.01in;height:0.16in" src="http://darwin.test/garrido-transportes/public/img/002/vi_86.png" />
<img style="position:absolute;top:4.47in;left:8.71in;width:0.01in;height:0.16in" src="http://darwin.test/garrido-transportes/public/img/002/vi_87.png" />
<img style="position:absolute;top:4.63in;left:0.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_88.png" />
<img style="position:absolute;top:4.63in;left:4.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_89.png" />
<img style="position:absolute;top:4.63in;left:4.88in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_90.png" />
<img style="position:absolute;top:4.63in;left:5.28in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_91.png" />
<img style="position:absolute;top:4.63in;left:8.71in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_92.png" />
<img style="position:absolute;top:4.63in;left:0.44in;width:0.01in;height:1.71in" src="http://darwin.test/garrido-transportes/public/img/002/vi_93.png" />
<img style="position:absolute;top:4.63in;left:4.44in;width:0.01in;height:1.71in" src="http://darwin.test/garrido-transportes/public/img/002/vi_94.png" />
<img style="position:absolute;top:4.63in;left:4.88in;width:0.01in;height:1.71in" src="http://darwin.test/garrido-transportes/public/img/002/vi_95.png" />
<img style="position:absolute;top:4.63in;left:5.28in;width:0.01in;height:1.71in" src="http://darwin.test/garrido-transportes/public/img/002/vi_96.png" />
<img style="position:absolute;top:4.63in;left:8.71in;width:0.01in;height:1.71in" src="http://darwin.test/garrido-transportes/public/img/002/vi_97.png" />
<div style="position:absolute;top:6.35in;left:0.45in;width:3.74in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000">2. Esta experimentando alguno de estos síntomas?</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.53in;left:0.77in;width:0.11in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.53in;left:1.09in;width:2.60in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">fiebre </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">tos seca persistente </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">dificultad para respirar </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">dolor de garganta </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">náuseas vómitos </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">diarrea </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">pérdida del sentido del olfato o del gusto </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.01in;left:0.66in;width:3.53in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000">¿Experimenta alguno de los siguientes puntos y</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.18in;left:0.66in;width:2.83in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000">más allá de lo que puede experimentar</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.36in;left:0.88in;width:1.08in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000">normalmente?</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.53in;left:0.80in;width:0.12in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.53in;left:1.07in;width:1.51in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">resfriado </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">dolor muscular </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">fatiga </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">dolor de cabeza </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">nariz con secreciones</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">congestión nasal </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">pérdida de apetito </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.35in;left:4.55in;width:0.27in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#20201e">NO</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#20201e"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.55in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:6.74in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:6.94in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:7.14in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:7.33in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:7.53in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:7.72in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:8.45in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:8.64in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:8.84in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:9.03in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:9.23in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:9.43in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<div style="position:absolute;top:9.62in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:6.35in;left:4.88in;width:0.39in;height:3.65in" src="http://darwin.test/garrido-transportes/public/img/002/vi_98.png" />
<img style="position:absolute;top:6.35in;left:4.88in;width:0.39in;height:0.17in" src="http://darwin.test/garrido-transportes/public/img/002/vi_99.png" />
<div style="position:absolute;top:6.35in;left:5.01in;width:0.19in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#c61d2c">SI</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#c61d2c"> </span><br/></SPAN></div>
<img style="position:absolute;top:6.52in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_100.png" />
<div style="position:absolute;top:6.55in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:6.72in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_101.png" />
<div style="position:absolute;top:6.74in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:6.92in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_102.png" />
<div style="position:absolute;top:6.94in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:7.11in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_103.png" />
<div style="position:absolute;top:7.14in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:7.31in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_104.png" />
<div style="position:absolute;top:7.33in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:7.51in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_105.png" />
<div style="position:absolute;top:7.53in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:7.70in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_106.png" />
<div style="position:absolute;top:7.72in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:7.90in;left:4.88in;width:0.39in;height:0.17in" src="http://darwin.test/garrido-transportes/public/img/002/vi_107.png" />
<img style="position:absolute;top:8.07in;left:4.88in;width:0.39in;height:0.17in" src="http://darwin.test/garrido-transportes/public/img/002/vi_108.png" />
<img style="position:absolute;top:8.25in;left:4.88in;width:0.39in;height:0.17in" src="http://darwin.test/garrido-transportes/public/img/002/vi_109.png" />
<img style="position:absolute;top:8.42in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_110.png" />
<div style="position:absolute;top:8.45in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:8.62in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_111.png" />
<div style="position:absolute;top:8.64in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:8.81in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_112.png" />
<div style="position:absolute;top:8.84in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:9.01in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_113.png" />
<div style="position:absolute;top:9.03in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:9.21in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_114.png" />
<div style="position:absolute;top:9.23in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:9.40in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_115.png" />
<div style="position:absolute;top:9.43in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:9.60in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_116.png" />
<div style="position:absolute;top:9.62in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:9.80in;left:4.88in;width:0.39in;height:0.17in" src="http://darwin.test/garrido-transportes/public/img/002/vi_117.png" />
<div style="position:absolute;top:6.36in;left:5.37in;width:0.25in;line-height:0.27in;"><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:Arial;color:#ff0000">→</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.41in;left:5.73in;width:0.18in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">Si</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.41in;left:5.37in;width:1.41in;line-height:0.20in;"><DIV style="position:relative; left:0.63in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">respondió</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></DIV><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">preguntas</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.41in;left:6.88in;width:0.18in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">SI</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.41in;left:7.16in;width:0.13in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">a</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.41in;left:7.38in;width:0.53in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">alguna</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.41in;left:8.01in;width:0.75in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">de </span></SPAN><br/></div>
<div style="position:absolute;top:6.41in;left:8.01in;width:0.75in;line-height:0.22in;"><DIV style="position:relative; left:0.32in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">estas</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:6.77in;left:5.37in;width:0.12in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.77in;left:5.65in;width:3.04in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">no vaya a trabajar </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">llame a su supervisor para informarle que no</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">estará en su trabajo.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.29in;left:5.37in;width:0.12in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.30in;left:5.65in;width:3.07in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">llamada normal por ausencia laboral</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">completar </span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000">cuestionario </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">y enviarlo a su</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">supervisor para   ayudarnos   a   proteger   a </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">sus compañeros de trabajo</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.00in;left:5.37in;width:0.12in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.00in;left:5.65in;width:2.93in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">si el resultado del test es positivo para</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">COVID-19, comuníquese de inmediato con</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">su supervisor para ayudarnos a proteger a</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">sus compañeros</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:6.34in;left:0.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_118.png" />
<img style="position:absolute;top:6.34in;left:0.45in;width:3.99in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_119.png" />
<img style="position:absolute;top:6.34in;left:4.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_120.png" />
<img style="position:absolute;top:6.34in;left:4.45in;width:0.43in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_121.png" />
<img style="position:absolute;top:6.34in;left:4.88in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_122.png" />
<img style="position:absolute;top:6.34in;left:4.88in;width:0.39in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_123.png" />
<img style="position:absolute;top:6.34in;left:5.28in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_124.png" />
<img style="position:absolute;top:6.34in;left:5.28in;width:3.43in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_125.png" />
<img style="position:absolute;top:6.34in;left:8.71in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_126.png" />
<img style="position:absolute;top:6.35in;left:0.44in;width:0.01in;height:3.65in" src="http://darwin.test/garrido-transportes/public/img/002/vi_127.png" />
<img style="position:absolute;top:6.35in;left:4.44in;width:0.01in;height:3.65in" src="http://darwin.test/garrido-transportes/public/img/002/vi_128.png" />
<img style="position:absolute;top:6.35in;left:4.88in;width:0.01in;height:3.65in" src="http://darwin.test/garrido-transportes/public/img/002/vi_129.png" />
<img style="position:absolute;top:6.35in;left:5.28in;width:0.01in;height:3.65in" src="http://darwin.test/garrido-transportes/public/img/002/vi_130.png" />
<img style="position:absolute;top:6.35in;left:8.71in;width:0.01in;height:3.65in" src="http://darwin.test/garrido-transportes/public/img/002/vi_131.png" />
<div style="position:absolute;top:10.01in;left:0.45in;width:3.74in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000">3. Esta experimentando alguno de estos síntomas?</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.18in;left:0.80in;width:0.12in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.18in;left:1.07in;width:2.63in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">severa dificultad al respirar (ej.,</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">dificultad con respiración, hablando en</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">palabras sueltas)</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">dolor intenso en el pecho </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">sentirse confundido </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">reciente pérdida de conciencia </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">incapacidad de acostarse debido a</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">dificultad respiratoria.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.70in;left:0.80in;width:0.12in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.61in;left:0.80in;width:0.12in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.61in;left:1.07in;width:2.63in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">Otras condiciones de salud con las</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">que tenga dificultad debido a su actual</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">enfermedad respiratoria.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.01in;left:4.55in;width:0.27in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#20201e">NO</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#20201e"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.20in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#20201e">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#20201e"></span><br/></SPAN></div>
<div style="position:absolute;top:10.74in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#20201e">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#20201e"></span><br/></SPAN></div>
<div style="position:absolute;top:10.94in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#20201e">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#20201e"></span><br/></SPAN></div>
<div style="position:absolute;top:11.14in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#20201e">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#20201e"></span><br/></SPAN></div>
<div style="position:absolute;top:11.33in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#20201e">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#20201e"></span><br/></SPAN></div>
<div style="position:absolute;top:11.70in;left:4.59in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#20201e">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#20201e"></span><br/></SPAN></div>
<img style="position:absolute;top:10.00in;left:4.88in;width:0.39in;height:2.77in" src="http://darwin.test/garrido-transportes/public/img/002/vi_132.png" />
<img style="position:absolute;top:10.00in;left:4.88in;width:0.39in;height:0.17in" src="http://darwin.test/garrido-transportes/public/img/002/vi_133.png" />
<div style="position:absolute;top:10.01in;left:5.01in;width:0.19in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#c61d2c">SI</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#c61d2c"> </span><br/></SPAN></div>
<img style="position:absolute;top:10.18in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_134.png" />
<div style="position:absolute;top:10.20in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:10.37in;left:4.88in;width:0.39in;height:0.17in" src="http://darwin.test/garrido-transportes/public/img/002/vi_135.png" />
<img style="position:absolute;top:10.55in;left:4.88in;width:0.39in;height:0.17in" src="http://darwin.test/garrido-transportes/public/img/002/vi_136.png" />
<img style="position:absolute;top:10.72in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_137.png" />
<div style="position:absolute;top:10.74in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:10.92in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_138.png" />
<div style="position:absolute;top:10.94in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:11.11in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_139.png" />
<div style="position:absolute;top:11.14in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:11.31in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_140.png" />
<div style="position:absolute;top:11.33in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:11.51in;left:4.88in;width:0.39in;height:0.17in" src="http://darwin.test/garrido-transportes/public/img/002/vi_141.png" />
<img style="position:absolute;top:11.68in;left:4.88in;width:0.39in;height:0.20in" src="http://darwin.test/garrido-transportes/public/img/002/vi_142.png" />
<div style="position:absolute;top:11.70in;left:5.00in;width:0.30in;line-height:0.15in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000">☐</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:MS Gothic;color:#000000"></span><br/></SPAN></div>
<img style="position:absolute;top:11.88in;left:4.88in;width:0.39in;height:0.17in" src="http://darwin.test/garrido-transportes/public/img/002/vi_143.png" />
<div style="position:absolute;top:10.01in;left:5.37in;width:0.43in;line-height:0.30in;"><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:Arial;color:#ff0000">→</span><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:Arial;color:#ff0000"></span><br/></SPAN></div>
<div style="position:absolute;top:10.06in;left:5.73in;width:0.18in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">Si</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.06in;left:5.37in;width:1.41in;line-height:0.20in;"><DIV style="position:relative; left:0.63in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">respondió</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></DIV><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">preguntas</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.06in;left:6.88in;width:0.18in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">SI</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.06in;left:7.16in;width:0.13in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">a</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.06in;left:7.38in;width:0.53in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">alguna</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.06in;left:8.01in;width:0.75in;line-height:0.22in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">de </span></SPAN><br/></div>
<div style="position:absolute;top:10.06in;left:8.01in;width:0.75in;line-height:0.22in;"><DIV style="position:relative; left:0.32in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000">estas</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#ff0000"> </span><br/></SPAN></DIV></div>
<div style="position:absolute;top:10.42in;left:5.37in;width:0.12in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.43in;left:5.65in;width:2.63in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">no vaya a trabajar </span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000">y busque atención</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000">médica de inmediato</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.77in;left:5.37in;width:0.12in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:10.78in;left:5.65in;width:3.04in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">llame a su supervisor para informarle que no</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">estará en su trabajo.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.12in;left:5.37in;width:0.12in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.13in;left:5.65in;width:2.67in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">llamada normal por ausencia laboral</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">completar </span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000">cuestionario</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> y enviarlo a su</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.48in;left:5.65in;width:3.07in;line-height:0.19in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">supervisor para   ayudarnos   a   proteger   a </span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">sus compañeros de trabajo</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.82in;left:5.37in;width:0.12in;line-height:0.21in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:Calibri;color:#000000">•</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:11.83in;left:5.65in;width:2.93in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">si el resultado del test es positivo para</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">COVID-19, comuníquese de inmediato con</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">su supervisor para ayudarnos a proteger a</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">sus compañeros</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:9.99in;left:0.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_144.png" />
<img style="position:absolute;top:9.99in;left:0.45in;width:3.99in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_145.png" />
<img style="position:absolute;top:9.99in;left:4.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_146.png" />
<img style="position:absolute;top:9.99in;left:4.45in;width:0.43in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_147.png" />
<img style="position:absolute;top:9.99in;left:4.88in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_148.png" />
<img style="position:absolute;top:9.99in;left:4.88in;width:0.39in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_149.png" />
<img style="position:absolute;top:9.99in;left:5.28in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_150.png" />
<img style="position:absolute;top:9.99in;left:5.28in;width:3.43in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_151.png" />
<img style="position:absolute;top:9.99in;left:8.71in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_152.png" />
<img style="position:absolute;top:10.00in;left:0.44in;width:0.01in;height:2.77in" src="http://darwin.test/garrido-transportes/public/img/002/vi_153.png" />
<img style="position:absolute;top:12.77in;left:0.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_154.png" />
<img style="position:absolute;top:12.77in;left:0.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_155.png" />
<img style="position:absolute;top:12.77in;left:0.45in;width:3.99in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_156.png" />
<img style="position:absolute;top:10.00in;left:4.44in;width:0.01in;height:2.77in" src="http://darwin.test/garrido-transportes/public/img/002/vi_157.png" />
<img style="position:absolute;top:12.77in;left:4.44in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_158.png" />
<img style="position:absolute;top:12.77in;left:4.45in;width:0.43in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_159.png" />
<img style="position:absolute;top:10.00in;left:4.88in;width:0.01in;height:2.77in" src="http://darwin.test/garrido-transportes/public/img/002/vi_160.png" />
<img style="position:absolute;top:12.77in;left:4.88in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_161.png" />
<img style="position:absolute;top:12.77in;left:4.88in;width:0.39in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_162.png" />
<img style="position:absolute;top:10.00in;left:5.28in;width:0.01in;height:2.77in" src="http://darwin.test/garrido-transportes/public/img/002/vi_163.png" />
<img style="position:absolute;top:12.77in;left:5.28in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_164.png" />
<img style="position:absolute;top:12.77in;left:5.28in;width:3.43in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_165.png" />
<img style="position:absolute;top:10.00in;left:8.71in;width:0.01in;height:2.77in" src="http://darwin.test/garrido-transportes/public/img/002/vi_166.png" />
<img style="position:absolute;top:12.77in;left:8.71in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_167.png" />
<img style="position:absolute;top:12.77in;left:8.71in;width:0.01in;height:0.01in" src="http://darwin.test/garrido-transportes/public/img/002/vi_168.png" />
<div style="position:absolute;top:0.63in;left:0.87in;width:0.48in;line-height:0.78in;"><span style="font-style:normal;font-weight:bold;font-size:36pt;font-family:Arial-BoldMT;color:#5b9bd5">T</span><span style="font-style:normal;font-weight:bold;font-size:36pt;font-family:Arial-BoldMT;color:#5b9bd5"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.63in;left:1.14in;width:1.69in;line-height:0.78in;"><span style="font-style:normal;font-weight:bold;font-size:36pt;font-family:Arial-BoldMT;color:#5b9bd5">oma 5</span><span style="font-style:normal;font-weight:bold;font-size:36pt;font-family:Arial-BoldMT;color:#5b9bd5"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.26in;left:0.87in;width:2.93in;line-height:0.51in;"><span style="font-style:normal;font-weight:bold;font-size:26pt;font-family:Arial-BoldMT;color:#ffffff">para limitar la</span><span style="font-style:normal;font-weight:bold;font-size:26pt;font-family:Arial-BoldMT;color:#ffffff"> </span><br/><span style="font-style:normal;font-weight:bold;font-size:26pt;font-family:Arial-BoldMT;color:#ffffff">propagación</span><span style="font-style:normal;font-weight:bold;font-size:26pt;font-family:Arial-BoldMT;color:#ffffff"> </span><br/></SPAN></div>
<img style="position:absolute;top:1.06in;left:5.03in;width:3.45in;height:2.45in" src="http://darwin.test/garrido-transportes/public/img/002/vi_169.png" />
<div style="position:absolute;top:1.12in;left:5.14in;width:3.13in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">Alineados con nuestro valor fundamental de</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">salud y seguridad, Teck se está tomando muy</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">en serio la pandemia de COVID-19.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">Necesitamos trabajar juntos para limitar la</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">propagación y cuidarnos a nosotros mismo, a</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">nuestras familias y a los demás.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.34in;left:5.14in;width:3.15in;line-height:0.18in;"><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">Por favor tómate 5 minutos para completar las</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">siguientes preguntas y ayudarnos los unos a</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000">los otros a mantenernos saludables.</span><span style="font-style:normal;font-weight:normal;font-size:8pt;font-family:ArialMT;color:#000000"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.04in;left:5.14in;width:2.92in;line-height:0.20in;"><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000">Todos regresan a casa sanos y seguros</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000"> </span><br/><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000">todos los días</span><span style="font-style:normal;font-weight:bold;font-size:8pt;font-family:Arial-BoldMT;color:#000000"> </span><br/></SPAN></div>
<img style="position:absolute;top:0.31in;left:6.99in;width:1.74in;height:0.55in" src="http://darwin.test/garrido-transportes/public/img/002/ri_1.png" />
</body>
</html>
